from typing import Optional, Dict, Any, List, Protocol

class Repo(Protocol):
    def get_user(self, user_id: str) -> Dict[str, Any]: ...
    def upsert_user(self, user_id: str, patch: Dict[str, Any]) -> None: ...
    def get_active_weekly_session(self, user_id: str, week: int) -> Optional[Dict[str, Any]]: ...
    def create_weekly_session(self, user_id: str, week: int) -> Dict[str, Any]: ...
    def save_message(self, user_id: str, session_type: str, week: int, role: str, text: str) -> None: ...
    def update_progress(self, user_id: str, week: int, exit_hit: bool) -> None: ...
    def last_seen_touch(self, user_id: str) -> None: ...
    def get_messages(self, user_id: str, week: int) -> List[Dict[str, Any]]: ... # [추가] 대화 기록 로드를 위한 인터페이스